In [2]:
import pandas as pd

In [3]:
data = [['harry',45],['jill',67],['jacob',45],['shubhm',45]] #list of list

In [4]:
data

[['harry', 45], ['jill', 67], ['jacob', 45], ['shubhm', 45]]

In [5]:
pd.DataFrame(data , columns = ['Name','Marks'])

     Name  Marks
0   harry     45
1    jill     67
2   jacob     45
3  shubhm     45

In [6]:
data2 = { 'a':[2,34,55] , 'b':[45,34,66]}

In [7]:
df = pd.DataFrame(data2)

In [8]:
df

    a   b
0   2  45
1  34  34
2  55  66

## using numpy

In [9]:
import numpy as np

In [10]:
arr = np.array([[1,2],[4,6]])

In [11]:
df2 = pd.DataFrame(arr , columns=['a','b'])

In [12]:
df2

   a  b
0  1  2
1  4  6

In [14]:
df3 = pd.read_excel("excelSheet.xlsx")

In [15]:
df3

     Name  school  marks
0  bajrang   bdsm      56
1    yash     kkc      34
2    rahul   tttc      88
3   ankit     eec      56
4    mohan   sdct      90
5     kalu    wew      45

In [16]:
df4 = pd.read_csv('csvFile.csv')

In [17]:
df4

     Name  school  marks
0  bajrang   bdsm      56
1    yash     kkc      34
2    rahul   tttc      88
3   ankit     eec      56
4    mohan   sdct      90
5     kalu    wew      45

In [18]:
df5 = pd.read_json('data.json')

In [20]:
df5

      name    lang
0  bajrang  python
1    yadav  python
2    yadav  python

In [22]:
url = "https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv"
df = pd.read_csv(url)

In [23]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [24]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [26]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [29]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [31]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [32]:
df.shape

(244, 7)