In [4]:
import pandas  as pd

In [6]:
df = pd.read_csv("3_for03_DataSelection.csv")

In [7]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [8]:
df['Actor']

0         Shah Rukh Khan
1            Salman Khan
2             Aamir Khan
3          Ranbir Kapoor
4          Ranveer Singh
5     Ayushmann Khurrana
6          Rajkummar Rao
7         Hrithik Roshan
8           Akshay Kumar
9          Kartik Aaryan
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [10]:
df["Actor"][3]

'Ranbir Kapoor'

In [11]:
df[['Actor','Film']]

                 Actor                      Film
0       Shah Rukh Khan                   Pathaan
1          Salman Khan           Tiger Zinda Hai
2           Aamir Khan                    Dangal
3        Ranbir Kapoor                Brahmastra
4        Ranveer Singh                 Padmaavat
5   Ayushmann Khurrana                 Andhadhun
6        Rajkummar Rao                     Stree
7       Hrithik Roshan                       War
8         Akshay Kumar                Good Newwz
9        Kartik Aaryan         Bhool Bhulaiyaa 2
10        Varun Dhawan     Badrinath Ki Dulhania
11       Vicky Kaushal  Uri: The Surgical Strike

In [12]:
df.loc[5]

Actor                   Ayushmann Khurrana
Film                             Andhadhun
Year                                  2018
Genre                             Thriller
BoxOffice(INR Crore)                   111
IMDb                                   8.3
Name: 5, dtype: object

In [13]:
df.iloc[5]

Actor                   Ayushmann Khurrana
Film                             Andhadhun
Year                                  2018
Genre                             Thriller
BoxOffice(INR Crore)                   111
IMDb                                   8.3
Name: 5, dtype: object

## [ loc -> by label ]          [ iloc -> by position or index ]

In [16]:
df.loc[8,'IMDb']

np.float64(7.0)

In [17]:
df.iloc[8,5]

np.float64(7.0)

In [19]:
df.loc[0:4,['Actor','Film','IMDb']]

            Actor             Film  IMDb
0  Shah Rukh Khan          Pathaan   7.2
1     Salman Khan  Tiger Zinda Hai   6.0
2      Aamir Khan           Dangal   8.4
3   Ranbir Kapoor       Brahmastra   5.6
4   Ranveer Singh        Padmaavat   7.0

In [20]:
df.iloc[0:2,0:2]

            Actor             Film
0  Shah Rukh Khan          Pathaan
1     Salman Khan  Tiger Zinda Hai

In [22]:
df.iat[0,3]

'Action'

In [23]:
df.at[5,'Genre']

'Thriller'

In [26]:
df[df['IMDb']>6]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [28]:
df[df['IMDb']>7]['Actor']

0         Shah Rukh Khan
2             Aamir Khan
5     Ayushmann Khurrana
6          Rajkummar Rao
11         Vicky Kaushal
Name: Actor, dtype: object

In [29]:
df[(df['IMDb']>7 ) & (df['Year']>2022)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [30]:
df.query("Year > 2020 and IMDb > 7")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2