In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("3_for03_DataSelection.csv")

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [87]:
df['Actor'][1:5]

1      Salman Khan
2       Aamir Khan
3    Ranbir Kapoor
4    Ranveer Singh
Name: Actor, dtype: object

In [31]:
df[['Actor','IMDb']]

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [84]:
df.loc[1:7,'Actor']

1           Salman Khan
2            Aamir Khan
3         Ranbir Kapoor
4         Ranveer Singh
5    Ayushmann Khurrana
6         Rajkummar Rao
7        Hrithik Roshan
Name: Actor, dtype: object

In [37]:
df.iloc[3,3]

'Fantasy'

In [39]:
df.loc[1:5,'Actor':'Year']

                Actor             Film  Year
1         Salman Khan  Tiger Zinda Hai  2017
2          Aamir Khan           Dangal  2016
3       Ranbir Kapoor       Brahmastra  2022
4       Ranveer Singh        Padmaavat  2018
5  Ayushmann Khurrana        Andhadhun  2018

In [42]:
df.loc[1:5,['Actor',"Year","IMDb"]]

                Actor  Year  IMDb
1         Salman Khan  2017   6.0
2          Aamir Khan  2016   8.4
3       Ranbir Kapoor  2022   5.6
4       Ranveer Singh  2018   7.0
5  Ayushmann Khurrana  2018   8.3

In [43]:
df.iloc[1:4,0:4]

           Actor             Film  Year      Genre
1    Salman Khan  Tiger Zinda Hai  2017     Action
2     Aamir Khan           Dangal  2016  Biography
3  Ranbir Kapoor       Brahmastra  2022    Fantasy

In [47]:
df.at[1,'Film']

'Tiger Zinda Hai'

In [48]:
df.iat[0,5]

np.float64(7.2)

In [53]:
df[(df['IMDb']>8) & (df['Year']>2020)]

Empty DataFrame
Columns: [Actor, Film, Year, Genre, BoxOffice(INR Crore), IMDb]
Index: []

In [54]:
df[df['IMDb']>8]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [56]:
df.query('IMDb > 7')

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [59]:
df2 = df[['Actor','IMDb']]

In [60]:
df2

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [107]:
df2['Actor'][0]

'bajrang'

In [108]:
df2

                    Actor     IMDb
0                 bajrang      7.2
1                  roshan      6.0
2              Aamir Khan      8.4
3           Ranbir Kapoor      5.6
4           Ranveer Singh      7.0
5      Ayushmann Khurrana      8.3
6           Rajkummar Rao      7.5
7          Hrithik Roshan      6.5
8            Akshay Kumar      7.0
9           Kartik Aaryan      5.9
10           Varun Dhawan      6.1
11          Vicky Kaushal      8.2
Actor             bajrang  bajrang

In [109]:
df2.loc[1,'Actor'] = 'roshan'

KeyError: 'bajrang'