In [108]:
import pandas as pd

In [109]:
df = pd.read_csv('3_for03_DataSelection.csv')

In [110]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [111]:
df.sort_values("Year",ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [112]:
df2 = df.sort_values(["Year","IMDb"] , ascending=False).copy()

In [113]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [114]:
df2.reset_index(drop = True,inplace = True)  # jab purana index nahi chaheye

In [115]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
5,Hrithik Roshan,War,2019,Action,475,6.5
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [116]:
df3 = df.sort_values("Year")

In [117]:
df3

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [118]:
df3.sort_index()

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [119]:
df2["Rank"]= df2["IMDb"].rank(ascending = False,method="dense")

In [120]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,7.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [121]:
df2.rename(columns={"Actor":"natak khore"},inplace = True)

In [122]:
df2

,natak khore,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
2,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
3,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0
4,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
5,Hrithik Roshan,War,2019,Action,475,6.5,7.0
6,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
7,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
8,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
9,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
10,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
11,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0

In [123]:
df = df[["Film","IMDb","Year","Actor","Genre","BoxOffice(INR Crore)"]]

In [124]:
df

,Film,IMDb,Year,Actor,Genre,BoxOffice(INR Crore)
0,Pathaan,7.2,2023,Shah Rukh Khan,Action,1050
1,Tiger Zinda Hai,6.0,2017,Salman Khan,Action,565
2,Dangal,8.4,2016,Aamir Khan,Biography,2024
3,Brahmastra,5.6,2022,Ranbir Kapoor,Fantasy,431
4,Padmaavat,7.0,2018,Ranveer Singh,Historical,585
5,Andhadhun,8.3,2018,Ayushmann Khurrana,Thriller,111
6,Stree,7.5,2018,Rajkummar Rao,Horror Comedy,180
7,War,6.5,2019,Hrithik Roshan,Action,475
8,Good Newwz,7.0,2019,Akshay Kumar,Comedy,318
9,Bhool Bhulaiyaa 2,5.9,2022,Kartik Aaryan,Horror Comedy,266
10,Badrinath Ki Dulhania,6.1,2017,Varun Dhawan,Romantic Comedy,201
11,Uri: The Surgical Strike,8.2,2019,Vicky Kaushal,Action,342

In [125]:
df

,Film,IMDb,Year,Actor,Genre,BoxOffice(INR Crore)
0,Pathaan,7.2,2023,Shah Rukh Khan,Action,1050
1,Tiger Zinda Hai,6.0,2017,Salman Khan,Action,565
2,Dangal,8.4,2016,Aamir Khan,Biography,2024
3,Brahmastra,5.6,2022,Ranbir Kapoor,Fantasy,431
4,Padmaavat,7.0,2018,Ranveer Singh,Historical,585
5,Andhadhun,8.3,2018,Ayushmann Khurrana,Thriller,111
6,Stree,7.5,2018,Rajkummar Rao,Horror Comedy,180
7,War,6.5,2019,Hrithik Roshan,Action,475
8,Good Newwz,7.0,2019,Akshay Kumar,Comedy,318
9,Bhool Bhulaiyaa 2,5.9,2022,Kartik Aaryan,Horror Comedy,266
10,Badrinath Ki Dulhania,6.1,2017,Varun Dhawan,Romantic Comedy,201
11,Uri: The Surgical Strike,8.2,2019,Vicky Kaushal,Action,342