In [5]:
import pandas as pd

# sample DataFrame
data = {
    'Name':['Alice','Bob','charlie'],
    'Math':[85,78,92],
    'Science':[90,82,89],
    'English':[88,85,94]
}

df = pd.DataFrame(data)
print(df)

      Name  Math  Science  English
0    Alice    85       90       88
1      Bob    78       82       85
2  charlie    92       89       94

In [6]:
meltDf = df.melt(id_vars=["Name"],value_vars=["Math","Science","English"],var_name="Subject",value_name="Score")

In [9]:
meltDf

      Name  Subject  Score
0    Alice     Math     85
1      Bob     Math     78
2  charlie     Math     92
3    Alice  Science     90
4      Bob  Science     82
5  charlie  Science     89
6    Alice  English     88
7      Bob  English     85
8  charlie  English     94

In [11]:
meltDf.pivot(index="Name", columns="Subject", values="Score")

Subject  English  Math  Science
Name
Alice         88    85       90
Bob           85    78       82
charlie       94    92       89