In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [3]:
df

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [6]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [8]:
df.groupby("Team")["Age"].sum()

Team
A    48
B    52
C    54
D    48
Name: Age, dtype: int64

In [9]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
Marketing    92
Sales        80
Name: Salary, dtype: int64

In [12]:
df.groupby("Department")["Salary"].agg(["min","max","mean"])  # this return dataframe not a  series

            min  max  mean
Department
HR           85   90  87.5
IT           78   85  81.5
Marketing    88   92  90.0
Sales        75   80  77.5

In [13]:
type(df.groupby("Department")["Salary"].agg(["min","max","mean"]))

pandas.core.frame.DataFrame

In [17]:
df.groupby("Department")["Salary"].agg(minimum_score = "min",avg_score = "mean")

            minimum_score  avg_score
Department
HR                     85       87.5
IT                     78       81.5
Marketing              88       90.0
Sales                  75       77.5

In [18]:
df.groupby("Department")["Salary"].aggregate(minimum_score = "min",avg_score = "mean")

            minimum_score  avg_score
Department
HR                     85       87.5
IT                     78       81.5
Marketing              88       90.0
Sales                  75       77.5

In [19]:
df["Team_Avg"] = df.groupby("Department")["Salary"].transform("mean")

In [20]:
df

  Department Team Gender  Salary  Age   JoinDate  Team_Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [21]:
df

  Department Team Gender  Salary  Age   JoinDate  Team_Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
2         IT    B      M      78   30 2021-03-20      81.5
3         IT    B      F      85   22 2021-04-10      81.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0
6      Sales    D      M      75   21 2021-07-15      77.5
7      Sales    D      F      80   27 2021-08-01      77.5

In [22]:
df.groupby("Department").filter(lambda x:x["Salary"].mean() > 85)

  Department Team Gender  Salary  Age   JoinDate  Team_Avg
0         HR    A      M      85   23 2020-01-10      87.5
1         HR    A      F      90   25 2020-02-15      87.5
4  Marketing    C      M      92   28 2020-05-30      90.0
5  Marketing    C      F      88   26 2020-06-25      90.0