In [2]:
import pandas as pd
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
employees

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [4]:
departments

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [5]:
pd.merge(employees ,departments,on="DeptID")  # merge on the basis of common DepthID in employees and departments

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [6]:
pd.merge(employees,departments,on="DeptID",how="left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [7]:
pd.merge(employees,departments,on="DeptID",how="right")

   EmpID   Name  DeptID     DeptName
0    1.0  Alice      10           HR
1    2.0    Bob      20  Engineering
2    NaN    NaN      40    Marketing

In [8]:
pd.merge(employees,departments,on="DeptID",how="outer")

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

## concatination

In [13]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"],"Score": [432,876]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],"age":[43,56]})

In [14]:
df1

    Name  Score
0  Alice    432
1    Bob    876

In [15]:
df2

      Name  age
0  Charlie   43
1    David   56

In [16]:
pd.concat([df1, df2],axis= 1)

    Name  Score     Name  age
0  Alice    432  Charlie   43
1    Bob    876    David   56

In [17]:
pd.concat([df1, df2])

      Name  Score   age
0    Alice  432.0   NaN
1      Bob  876.0   NaN
0  Charlie    NaN  43.0
1    David    NaN  56.0