In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("05_data_cleaning_sample.csv")

In [4]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [5]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [6]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [7]:
df.dropna(axis = 1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [8]:
df["Age group"] = df["Age"].apply(lambda x:"Alder" if x>25 else "young")

In [9]:
df

      Name   Age         City Gender              Email   Join Date Age group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     young
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     young
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     Alder
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     young
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     young
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     Alder
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     young
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     young
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     young

In [10]:
gender_map={"M":"Male","F":"Female","o":"other"}

df["Gender"] = df["Gender"].map(gender_map)

In [11]:
df

      Name   Age         City  Gender              Email   Join Date Age group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     young
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     Alder
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     Alder
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021     young
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021     young
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young

In [13]:
df['City'] = df['City'].replace({"New York":"New Delhi","Los Angeles":"Patal lok"})

In [14]:
df

      Name   Age       City  Gender              Email   Join Date Age group
0    Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie   NaN      Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Patal lok    Male    bob@example.com  15-06-2020     Alder
3  Charlie   NaN      Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0     Mumbai    Male  david@example.com  12-11-2019     young
5      NaN  28.0      Delhi  Female     eve@domain.com         NaN     Alder
6    Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young
7    Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young
8  Charlie   NaN      Delhi    Male    charlie@example  20-07-2021     young

In [16]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [17]:
df.dropna()

    Name   Age       City  Gender              Email   Join Date Age group
0  Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young
2    Bob  30.0  Patal lok    Male    bob@example.com  15-06-2020     Alder
4  David  22.0     Mumbai    Male  david@example.com  12-11-2019     young
6  Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young
7  Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young

In [19]:
df.drop_duplicates()

      Name   Age       City  Gender              Email   Join Date Age group
0    Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie   NaN      Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Patal lok    Male    bob@example.com  15-06-2020     Alder
4    David  22.0     Mumbai    Male  david@example.com  12-11-2019     young
5      NaN  28.0      Delhi  Female     eve@domain.com         NaN     Alder

In [20]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [21]:
df.drop_duplicates()

      Name   Age       City  Gender              Email   Join Date Age group
0    Alice  25.0  New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie   NaN      Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Patal lok    Male    bob@example.com  15-06-2020     Alder
4    David  22.0     Mumbai    Male  david@example.com  12-11-2019     young
5      NaN  28.0      Delhi  Female     eve@domain.com         NaN     Alder

In [22]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date  Age group
0  False  False  False   False  False      False      False
1  False   True  False   False  False      False      False
2  False  False  False   False  False      False      False
3  False   True  False   False  False      False      False
4  False  False  False   False  False      False      False
5   True  False  False   False  False       True      False
6  False  False  False   False  False      False      False
7  False  False  False   False  False      False      False
8  False   True  False   False  False      False      False