In [1]:
import pandas as pd

In [2]:
employees = pd.DataFrame({
    "EmpID": [1, 2, 3],
    "Name": ["Alice", "Bob", "Charlie"],
    "DeptID": [10, 20, 30]
})

departments = pd.DataFrame({
    "DeptID": [10, 20, 40],
    "DeptName": ["HR", "Engineering", "Marketing"]
})

In [3]:
df1 = pd.DataFrame(employees)
df2 = pd.DataFrame(departments)

In [4]:
df1

   EmpID     Name  DeptID
0      1    Alice      10
1      2      Bob      20
2      3  Charlie      30

In [5]:
df2

   DeptID     DeptName
0      10           HR
1      20  Engineering
2      40    Marketing

In [19]:
pd.merge(employees,departments,on = "DeptID")

   EmpID   Name  DeptID     DeptName
0      1  Alice      10           HR
1      2    Bob      20  Engineering

In [7]:
pd.merge(employees,departments,on = 'DeptID',how = "left")

   EmpID     Name  DeptID     DeptName
0      1    Alice      10           HR
1      2      Bob      20  Engineering
2      3  Charlie      30          NaN

In [8]:
pd.merge(employees,departments, on = 'DeptID',how= 'outer')

   EmpID     Name  DeptID     DeptName
0    1.0    Alice      10           HR
1    2.0      Bob      20  Engineering
2    3.0  Charlie      30          NaN
3    NaN      NaN      40    Marketing

In [17]:
df1 = pd.DataFrame({"Name": ["Alice", "Bob"], 'score':[2,3]})
df2 = pd.DataFrame({"Name": ["Charlie", "David"],'score':[3,6]})

pd.concat([df1, df2])

      Name  score
0    Alice      2
1      Bob      3
0  Charlie      3
1    David      6

In [15]:
pd.concat([df1,df2],axis = 1)

    Name  score     Name  score
0  Alice      2  Charlie      3
1    Bob      3    David      6