In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('05_data_cleaning_sample.csv')

In [3]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [4]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [5]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [6]:
df.dropna(axis=1)

          City Gender              Email
0     New York      F  alice@example.com
1        Delhi      M    charlie@example
2  Los Angeles      M    bob@example.com
3        Delhi      M    charlie@example
4       Mumbai      M  david@example.com
5        Delhi      F     eve@domain.com
6     New York      F  alice@example.com
7     New York      F  alice@example.com
8        Delhi      M    charlie@example

In [7]:
df.fillna('hello')

      Name    Age         City Gender              Email   Join Date
0    Alice   25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  hello        Delhi      M    charlie@example  20-07-2021
2      Bob   30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  hello        Delhi      M    charlie@example  20-07-2021
4    David   22.0       Mumbai      M  david@example.com  12-11-2019
5    hello   28.0        Delhi      F     eve@domain.com       hello
6    Alice   25.0     New York      F  alice@example.com  01-05-2021
7    Alice   25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  hello        Delhi      M    charlie@example  20-07-2021

In [8]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [9]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [10]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [11]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [12]:
df["Name"].str.capitalize()

0      Alice
1    Charlie
2        Bob
3    Charlie
4      David
5        NaN
6      Alice
7      Alice
8    Charlie
Name: Name, dtype: object

In [13]:
df['City'].str.contains("delhi", case=False)

0    False
1     True
2    False
3     True
4    False
5     True
6    False
7    False
8     True
Name: City, dtype: bool

In [14]:
df['Email'].str.split('@')

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
3      [charlie, example]
4    [david, example.com]
5       [eve, domain.com]
6    [alice, example.com]
7    [alice, example.com]
8      [charlie, example]
Name: Email, dtype: object

In [15]:
df2 = df.ffill().copy()

In [16]:
df2

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [17]:
df2['Age'] = df2['Age'].astype(int)

In [18]:
df2

      Name  Age         City Gender              Email   Join Date
0    Alice   25     New York      F  alice@example.com  01-05-2021
1  Charlie   25        Delhi      M    charlie@example  20-07-2021
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   30        Delhi      M    charlie@example  20-07-2021
4    David   22       Mumbai      M  david@example.com  12-11-2019
5    David   28        Delhi      F     eve@domain.com  12-11-2019
6    Alice   25     New York      F  alice@example.com  01-05-2021
7    Alice   25     New York      F  alice@example.com  01-05-2021
8  Charlie   25        Delhi      M    charlie@example  20-07-2021

In [19]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       9 non-null      object
 1   Age        9 non-null      int64
 2   City       9 non-null      object
 3   Gender     9 non-null      object
 4   Email      9 non-null      object
 5   Join Date  9 non-null      object
dtypes: int64(1), object(5)
memory usage: 564.0+ bytes

In [20]:
df2['Name'].str.upper()

0      ALICE
1    CHARLIE
2        BOB
3    CHARLIE
4      DAVID
5      DAVID
6      ALICE
7      ALICE
8    CHARLIE
Name: Name, dtype: object

In [21]:
df2

      Name  Age         City Gender              Email   Join Date
0    Alice   25     New York      F  alice@example.com  01-05-2021
1  Charlie   25        Delhi      M    charlie@example  20-07-2021
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   30        Delhi      M    charlie@example  20-07-2021
4    David   22       Mumbai      M  david@example.com  12-11-2019
5    David   28        Delhi      F     eve@domain.com  12-11-2019
6    Alice   25     New York      F  alice@example.com  01-05-2021
7    Alice   25     New York      F  alice@example.com  01-05-2021
8  Charlie   25        Delhi      M    charlie@example  20-07-2021

In [22]:
df2['Age Group'] = df2["Age"].apply(lambda x: "Adult" if x>=22 else "minor")

In [23]:
df2

      Name  Age         City Gender              Email   Join Date Age Group
0    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
1  Charlie   25        Delhi      M    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles      M    bob@example.com  15-06-2020     Adult
3  Charlie   30        Delhi      M    charlie@example  20-07-2021     Adult
4    David   22       Mumbai      M  david@example.com  12-11-2019     Adult
5    David   28        Delhi      F     eve@domain.com  12-11-2019     Adult
6    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
7    Alice   25     New York      F  alice@example.com  01-05-2021     Adult
8  Charlie   25        Delhi      M    charlie@example  20-07-2021     Adult

In [24]:
mape = { 'M':'Male' , 'F':'Female' }
df2['Gender'] = df2['Gender'].map(mape)

In [25]:
df2

      Name  Age         City  Gender              Email   Join Date Age Group
0    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
1  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult
2      Bob   30  Los Angeles    Male    bob@example.com  15-06-2020     Adult
3  Charlie   30        Delhi    Male    charlie@example  20-07-2021     Adult
4    David   22       Mumbai    Male  david@example.com  12-11-2019     Adult
5    David   28        Delhi  Female     eve@domain.com  12-11-2019     Adult
6    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
7    Alice   25     New York  Female  alice@example.com  01-05-2021     Adult
8  Charlie   25        Delhi    Male    charlie@example  20-07-2021     Adult

In [34]:
df2['City'] = df2['City'].replace({'Delhi':'New Delhi', 'Los Angeles':'locknow'})

In [35]:
df2

,Name,Age,City,Gender,Email,Join Date,Age Group,city
0,Alice,25,New York,Female,alice@example.com,01-05-2021,Adult,New York
1,Charlie,25,New Delhi,Male,charlie@example,20-07-2021,Adult,New Delhi
2,Bob,30,locknow,Male,bob@example.com,15-06-2020,Adult,locknow
3,Charlie,30,New Delhi,Male,charlie@example,20-07-2021,Adult,New Delhi
4,David,22,Mumbai,Male,david@example.com,12-11-2019,Adult,Mumbai
5,David,28,New Delhi,Female,eve@domain.com,12-11-2019,Adult,New Delhi
6,Alice,25,New York,Female,alice@example.com,01-05-2021,Adult,New York
7,Alice,25,New York,Female,alice@example.com,01-05-2021,Adult,New York
8,Charlie,25,New Delhi,Male,charlie@example,20-07-2021,Adult,New Delhi