In [2]:
import pandas as pd

In [3]:
df =  pd.read_csv("3_for03_DataSelection.csv")

In [4]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [5]:
df['Actor'][0]

'Shah Rukh Khan'

In [6]:
df[['Actor','Film','Year']]

                 Actor                      Film  Year
0       Shah Rukh Khan                   Pathaan  2023
1          Salman Khan           Tiger Zinda Hai  2017
2           Aamir Khan                    Dangal  2016
3        Ranbir Kapoor                Brahmastra  2022
4        Ranveer Singh                 Padmaavat  2018
5   Ayushmann Khurrana                 Andhadhun  2018
6        Rajkummar Rao                     Stree  2018
7       Hrithik Roshan                       War  2019
8         Akshay Kumar                Good Newwz  2019
9        Kartik Aaryan         Bhool Bhulaiyaa 2  2022
10        Varun Dhawan     Badrinath Ki Dulhania  2017
11       Vicky Kaushal  Uri: The Surgical Strike  2019

In [7]:
df.loc[3]

Actor                   Ranbir Kapoor
Film                       Brahmastra
Year                             2022
Genre                         Fantasy
BoxOffice(INR Crore)              431
IMDb                              5.6
Name: 3, dtype: object

In [8]:
df.loc[[0,1]]

            Actor             Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan          Pathaan  2023  Action                  1050   7.2
1     Salman Khan  Tiger Zinda Hai  2017  Action                   565   6.0

In [9]:
df.loc[0,"Actor"]

'Shah Rukh Khan'

In [10]:
df.iloc[0,0]

'Shah Rukh Khan'

In [11]:
df.loc[0:3,['Actor','IMDb']]

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4
3   Ranbir Kapoor   5.6

In [12]:
df.loc[[0,1,2,3]]

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [13]:
df.loc[0:4,['Actor','IMDb','Film']]

            Actor  IMDb             Film
0  Shah Rukh Khan   7.2          Pathaan
1     Salman Khan   6.0  Tiger Zinda Hai
2      Aamir Khan   8.4           Dangal
3   Ranbir Kapoor   5.6       Brahmastra
4   Ranveer Singh   7.0        Padmaavat

In [14]:
df.at[0,'Actor']

'Shah Rukh Khan'

In [15]:
df[df['IMDb']>7]['Actor']

0         Shah Rukh Khan
2             Aamir Khan
5     Ayushmann Khurrana
6          Rajkummar Rao
11         Vicky Kaushal
Name: Actor, dtype: object

In [16]:
df[(df["IMDb"]>7) & (df["Year"] > 2020)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [17]:
df.query(" IMDb> 7 and Year> 2000")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [18]:
df.query(" Year == 2020")

Empty DataFrame
Columns: [Actor, Film, Year, Genre, BoxOffice(INR Crore), IMDb]
Index: []

In [19]:
df2 = df[['Actor','IMDb']]

In [20]:
df2

                 Actor  IMDb
0       Shah Rukh Khan   7.2
1          Salman Khan   6.0
2           Aamir Khan   8.4
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [21]:
df['IMDb'][2]

np.float64(8.4)

In [22]:
df[['Actor','IMDb']][2:5]

           Actor  IMDb
2     Aamir Khan   8.4
3  Ranbir Kapoor   5.6
4  Ranveer Singh   7.0

In [23]:
df.loc[3:10,['Actor','IMDb']]

                 Actor  IMDb
3        Ranbir Kapoor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khurrana   8.3
6        Rajkummar Rao   7.5
7       Hrithik Roshan   6.5
8         Akshay Kumar   7.0
9        Kartik Aaryan   5.9
10        Varun Dhawan   6.1

In [25]:
df2 = df[['Actor','IMDb']][0:4]

In [26]:
df2

            Actor  IMDb
0  Shah Rukh Khan   7.2
1     Salman Khan   6.0
2      Aamir Khan   8.4
3   Ranbir Kapoor   5.6

In [27]:
df2.loc[0,'IMDb']= 3

In [28]:
df2

            Actor  IMDb
0  Shah Rukh Khan   3.0
1     Salman Khan   6.0
2      Aamir Khan   8.4
3   Ranbir Kapoor   5.6

In [29]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [30]:
df2 = df['Actor'][0:5]

In [33]:
df2

0    Shah Rukh Khan
1       Salman Khan
2        Aamir Khan
3     Ranbir Kapoor
4     Ranveer Singh
Name: Actor, dtype: object

'Shah Rukh Khan'