In [2]:
import pandas as pd

In [3]:
s = pd.Series([10,20,30,40,50],index=["1st","2nd","3rd","4th","5th"])

In [4]:
s

1st    10
2nd    20
3rd    30
4th    40
5th    50
dtype: int64

In [5]:
data = {
"name": ["Alice", "Bob", "Charlie"],
"age": [25, 30, 35],
"city": ["Delhi", "Mumbai", "Bangalore"]
}
df = pd.DataFrame(data)

In [6]:
df

      name  age       city
0    Alice   25      Delhi
1      Bob   30     Mumbai
2  Charlie   35  Bangalore

In [7]:
df.index

RangeIndex(start=0, stop=3, step=1)

In [8]:
df.columns

Index(['name', 'age', 'city'], dtype='object')

In [9]:
data = [
["Alice", 25],
["Bob", 30],
["Charlie", 35]
]

In [10]:
df = pd.DataFrame(data,columns=["Name","age"])

In [11]:
df

      Name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [12]:
import numpy as np
arr = np.array([[1,2],[3,4]])
df = pd.DataFrame(arr,columns=["A","B"])

In [13]:
df

   A  B
0  1  2
1  3  4

In [14]:
df.describe()

              A         B
count  2.000000  2.000000
mean   2.000000  3.000000
std    1.414214  1.414214
min    1.000000  2.000000
25%    1.500000  2.500000
50%    2.000000  3.000000
75%    2.500000  3.500000
max    3.000000  4.000000

In [15]:
df = pd.read_csv("3_for03_DataSelection.csv")

In [16]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [17]:
df.loc[[3,5]]

                Actor        Film  Year     Genre  BoxOffice(INR Crore)  IMDb
3       Ranbir Kapoor  Brahmastra  2022   Fantasy                   431   5.6
5  Ayushmann Khurrana   Andhadhun  2018  Thriller                   111   8.3

In [18]:
df.iloc[[3,5]]

                Actor        Film  Year     Genre  BoxOffice(INR Crore)  IMDb
3       Ranbir Kapoor  Brahmastra  2022   Fantasy                   431   5.6
5  Ayushmann Khurrana   Andhadhun  2018  Thriller                   111   8.3

In [19]:
df[(df["IMDb"]>7) & (df["Year"]>2022)]

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [20]:
df.query(" IMDb > 7 and Year > 2022")

            Actor     Film  Year   Genre  BoxOffice(INR Crore)  IMDb
0  Shah Rukh Khan  Pathaan  2023  Action                  1050   7.2

In [21]:
df.query(" Film == 'Stree'")

           Actor   Film  Year          Genre  BoxOffice(INR Crore)  IMDb
6  Rajkummar Rao  Stree  2018  Horror Comedy                   180   7.5

In [22]:
df = pd.read_csv("05_data_cleaning_sample.csv")

In [23]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [24]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [25]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [26]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [27]:
df.ffill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [28]:
df.drop_duplicates()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN

In [29]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [30]:
def fxn(x):
    return "elder" if x>25 else "young"

df["Age_Group"] = df["Age"].apply(fxn)

In [31]:
df

      Name   Age         City Gender              Email   Join Date Age_Group
0    Alice  25.0     New York      F  alice@example.com  01-05-2021     young
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     young
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020     elder
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     young
4    David  22.0       Mumbai      M  david@example.com  12-11-2019     young
5      NaN  28.0        Delhi      F     eve@domain.com         NaN     elder
6    Alice  25.0     New York      F  alice@example.com  01-05-2021     young
7    Alice  25.0     New York      F  alice@example.com  01-05-2021     young
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021     young

In [32]:
mapp = { "F":"Female","M":"Male","O":"other"}
df["Gender"]= df["Gender"].map(mapp)

In [33]:
df

      Name   Age         City  Gender              Email   Join Date Age_Group
0    Alice  25.0     New York  Female  alice@example.com  01-05-2021     young
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     elder
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     elder
6    Alice  25.0     New York  Female  alice@example.com  01-05-2021     young
7    Alice  25.0     New York  Female  alice@example.com  01-05-2021     young
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young

In [34]:
df["City"] = df["City"].replace({"New York":"New Delhi"})

In [35]:
df

      Name   Age         City  Gender              Email   Join Date Age_Group
0    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     elder
3  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young
5      NaN  28.0        Delhi  Female     eve@domain.com         NaN     elder
6    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
7    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
8  Charlie   NaN        Delhi    Male    charlie@example  20-07-2021     young

In [36]:
df2 = df.ffill()

In [37]:
df2

      Name   Age         City  Gender              Email   Join Date Age_Group
0    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     elder
3  Charlie  30.0        Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young
5    David  28.0        Delhi  Female     eve@domain.com  12-11-2019     elder
6    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
7    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
8  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young

In [38]:
df2.sort_values("Age",ascending = False,inplace= True)

In [39]:
df2

      Name   Age         City  Gender              Email   Join Date Age_Group
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     elder
3  Charlie  30.0        Delhi    Male    charlie@example  20-07-2021     young
5    David  28.0        Delhi  Female     eve@domain.com  12-11-2019     elder
0    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
6    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
7    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
8  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young

In [40]:
df2.sort_index()

      Name   Age         City  Gender              Email   Join Date Age_Group
0    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     elder
3  Charlie  30.0        Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young
5    David  28.0        Delhi  Female     eve@domain.com  12-11-2019     elder
6    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
7    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
8  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young

In [41]:
df2

      Name   Age         City  Gender              Email   Join Date Age_Group
2      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     elder
3  Charlie  30.0        Delhi    Male    charlie@example  20-07-2021     young
5    David  28.0        Delhi  Female     eve@domain.com  12-11-2019     elder
0    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
1  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
6    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
7    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
8  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
4    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young

In [42]:
df2.reset_index(drop = True ,inplace = True)   # drop = True hm use karthe hai jise purana index gayab ho jaye samja kya

In [43]:
df2

      Name   Age         City  Gender              Email   Join Date Age_Group
0      Bob  30.0  Los Angeles    Male    bob@example.com  15-06-2020     elder
1  Charlie  30.0        Delhi    Male    charlie@example  20-07-2021     young
2    David  28.0        Delhi  Female     eve@domain.com  12-11-2019     elder
3    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
4  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
5    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
6    Alice  25.0    New Delhi  Female  alice@example.com  01-05-2021     young
7  Charlie  25.0        Delhi    Male    charlie@example  20-07-2021     young
8    David  22.0       Mumbai    Male  david@example.com  12-11-2019     young

In [44]:
df["Rank"] = df["Age"].rank()

In [45]:
df

,Name,Age,City,Gender,Email,Join Date,Age_Group,Rank
0,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
1,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN
2,Bob,30.0,Los Angeles,Male,bob@example.com,15-06-2020,elder,6.0
3,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN
4,David,22.0,Mumbai,Male,david@example.com,12-11-2019,young,1.0
5,NaN,28.0,Delhi,Female,eve@domain.com,NaN,elder,5.0
6,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
7,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
8,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN

In [46]:
df.rename(columns={"Gender": "ling"}, inplace=True)

In [47]:
df

,Name,Age,City,ling,Email,Join Date,Age_Group,Rank
0,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
1,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN
2,Bob,30.0,Los Angeles,Male,bob@example.com,15-06-2020,elder,6.0
3,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN
4,David,22.0,Mumbai,Male,david@example.com,12-11-2019,young,1.0
5,NaN,28.0,Delhi,Female,eve@domain.com,NaN,elder,5.0
6,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
7,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
8,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN

In [49]:
df.rename(index={3:"row3"})

,Name,Age,City,ling,Email,Join Date,Age_Group,Rank
0,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
1,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN
2,Bob,30.0,Los Angeles,Male,bob@example.com,15-06-2020,elder,6.0
row3,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN
4,David,22.0,Mumbai,Male,david@example.com,12-11-2019,young,1.0
5,NaN,28.0,Delhi,Female,eve@domain.com,NaN,elder,5.0
6,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
7,Alice,25.0,New Delhi,Female,alice@example.com,01-05-2021,young,3.0
8,Charlie,NaN,Delhi,Male,charlie@example,20-07-2021,young,NaN