In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("DataSelection.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
def fxn(x):
    return "Good Actor" if x> 8 else "Average Actor" 
df["Best_Actor"] = df["IMDb"].apply(fxn)

In [5]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Best_Actor
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,Average Actor
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,Average Actor
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,Good Actor
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,Average Actor
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,Average Actor
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,Good Actor
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,Average Actor
7,Hrithik Roshan,War,2019,Action,475,6.5,Average Actor
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,Average Actor
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,Average Actor
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,Average Actor
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,Good Actor

In [6]:
df3 = pd.DataFrame({
    "Department": ["HR", "HR", "IT", "IT", "Marketing", "Marketing", "Sales", "Sales"],
    "Team": ["A", "A", "B", "B", "C", "C", "D", "D"],
    "Gender": ["M", "F", "M", "F", "M", "F", "M", "F"],
    "Salary": [85, 90, 78, 85, 92, 88, 75, 80],
    "Age": [23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate": pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [7]:
df3

  Department Team Gender  Salary  Age   JoinDate
0         HR    A      M      85   23 2020-01-10
1         HR    A      F      90   25 2020-02-15
2         IT    B      M      78   30 2021-03-20
3         IT    B      F      85   22 2021-04-10
4  Marketing    C      M      92   28 2020-05-30
5  Marketing    C      F      88   26 2020-06-25
6      Sales    D      M      75   21 2021-07-15
7      Sales    D      F      80   27 2021-08-01

In [9]:
df3.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
Marketing    90.0
Sales        77.5
Name: Salary, dtype: float64

In [10]:
df3.groupby("Department").agg({
    "Salary" : "mean",
    "Age"    : "max"
})

            Salary  Age
Department
HR            87.5   25
IT            81.5   30
Marketing     90.0   28
Sales         77.5   27