In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("DataSelection.csv")

In [3]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [4]:
df.sort_values("Year", ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [5]:
df.sort_values("IMDb",ascending=False)

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
7,Hrithik Roshan,War,2019,Action,475,6.5
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6

In [6]:
df2 = df.sort_values(["Year","IMDb"]).copy()

In [7]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [8]:
# df2.reset_index( drop=True , inplace=True)

In [9]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2

In [10]:
df2.sort_index(inplace=True)

In [11]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [12]:
df2["Rank"] = df2["IMDb"].rank( ascending=False ,  method="dense")

In [13]:
df2

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,5.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,9.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,1.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,11.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,2.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,10.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,3.0

In [14]:

 df2.rename(columns={"Actor": "natak_karne_wale"} , inplace=True)

In [15]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,Hrithik Roshan,War,2019,Action,475,6.5
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [16]:
df2 = df[["BoxOffice(INR Crore)","IMDb","Year","Genre","Film","Actor"]]

In [17]:
df2

,BoxOffice(INR Crore),IMDb,Year,Genre,Film,Actor
0,1050,7.2,2023,Action,Pathaan,Shah Rukh Khan
1,565,6.0,2017,Action,Tiger Zinda Hai,Salman Khan
2,2024,8.4,2016,Biography,Dangal,Aamir Khan
3,431,5.6,2022,Fantasy,Brahmastra,Ranbir Kapoor
4,585,7.0,2018,Historical,Padmaavat,Ranveer Singh
5,111,8.3,2018,Thriller,Andhadhun,Ayushmann Khurrana
6,180,7.5,2018,Horror Comedy,Stree,Rajkummar Rao
7,475,6.5,2019,Action,War,Hrithik Roshan
8,318,7.0,2019,Comedy,Good Newwz,Akshay Kumar
9,266,5.9,2022,Horror Comedy,Bhool Bhulaiyaa 2,Kartik Aaryan
10,201,6.1,2017,Romantic Comedy,Badrinath Ki Dulhania,Varun Dhawan
11,342,8.2,2019,Action,Uri: The Surgical Strike,Vicky Kaushal

In [18]:
df["Film"].str.upper()

0                      PATHAAN
1              TIGER ZINDA HAI
2                       DANGAL
3                   BRAHMASTRA
4                    PADMAAVAT
5                    ANDHADHUN
6                        STREE
7                          WAR
8                   GOOD NEWWZ
9            BHOOL BHULAIYAA 2
10       BADRINATH KI DULHANIA
11    URI: THE SURGICAL STRIKE
Name: Film, dtype: object

In [19]:
df["Film"].str.split(" ")

0                         [Pathaan]
1               [Tiger, Zinda, Hai]
2                          [Dangal]
3                      [Brahmastra]
4                       [Padmaavat]
5                       [Andhadhun]
6                           [Stree]
7                             [War]
8                     [Good, Newwz]
9             [Bhool, Bhulaiyaa, 2]
10        [Badrinath, Ki, Dulhania]
11    [Uri:, The, Surgical, Strike]
Name: Film, dtype: object

In [20]:
def fxn(x):
    return "good_movie" if x>8 else "Bad_or_Avg"
df2 = df["IMDb"].apply(fxn)

In [21]:
df2

0     Bad_or_Avg
1     Bad_or_Avg
2     good_movie
3     Bad_or_Avg
4     Bad_or_Avg
5     good_movie
6     Bad_or_Avg
7     Bad_or_Avg
8     Bad_or_Avg
9     Bad_or_Avg
10    Bad_or_Avg
11    good_movie
Name: IMDb, dtype: object

In [23]:
df.sort_values("IMDb")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
7,Hrithik Roshan,War,2019,Action,475,6.5
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
2,Aamir Khan,Dangal,2016,Biography,2024,8.4

In [26]:
df.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,7,Hrithik Roshan,War,2019,Action,475,6.5
8,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [27]:
df.reset_index()

,index,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb
0,0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2
1,1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0
2,2,Aamir Khan,Dangal,2016,Biography,2024,8.4
3,3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6
4,4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0
5,5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3
6,6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5
7,7,Hrithik Roshan,War,2019,Action,475,6.5
8,8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0
9,9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9
10,10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1
11,11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2

In [31]:
df["Rank"] = df["IMDb"].rank(method="dense")

In [29]:
df

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,8.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,12.0
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.5
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,11.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,9.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.5
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,10.0

In [33]:
df.sort_values("Rank")

,Actor,Film,Year,Genre,BoxOffice(INR Crore),IMDb,Rank
3,Ranbir Kapoor,Brahmastra,2022,Fantasy,431,5.6,1.0
9,Kartik Aaryan,Bhool Bhulaiyaa 2,2022,Horror Comedy,266,5.9,2.0
1,Salman Khan,Tiger Zinda Hai,2017,Action,565,6.0,3.0
10,Varun Dhawan,Badrinath Ki Dulhania,2017,Romantic Comedy,201,6.1,4.0
7,Hrithik Roshan,War,2019,Action,475,6.5,5.0
4,Ranveer Singh,Padmaavat,2018,Historical,585,7.0,6.0
8,Akshay Kumar,Good Newwz,2019,Comedy,318,7.0,6.0
0,Shah Rukh Khan,Pathaan,2023,Action,1050,7.2,7.0
6,Rajkummar Rao,Stree,2018,Horror Comedy,180,7.5,8.0
11,Vicky Kaushal,Uri: The Surgical Strike,2019,Action,342,8.2,9.0
5,Ayushmann Khurrana,Andhadhun,2018,Thriller,111,8.3,10.0
2,Aamir Khan,Dangal,2016,Biography,2024,8.4,11.0